name: Pull Request Federation Compatibility Check

on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  compatibility-attributes:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Generate schema file
        run: dotnet run --project Compatibility/Attributes/AttributeFirst.csproj schema export --output products.graphql 
      - name: Compatibility Test
        uses: apollographql/federation-subgraph-compatibility@v2
        with:
          compose: 'Compatibility/Attributes/docker-compose.yaml'
          schema: 'Compatibility/Attributes/products.graphql'
          debug: true
          token: ${{ secrets.token }}

  compatibility-codefirst:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Generate schema file
        run: dotnet run --project Compatibility/CodeFirst/CodeFirst.csproj schema export --output products.graphql 
      - name: Compatibility Test
        uses: apollographql/federation-subgraph-compatibility@v2
        with:
          compose: 'Compatibility/CodeFirst/docker-compose.yaml'
          schema: 'Compatibility/CodeFirst/products.graphql'
          debug: true
          token: ${{ secrets.token }}
